---
stages:
    - build

build:
    stage: build
    image: golang
    tags:
        - docker
    script:
        - go version
        # Downloading dependencies
        - go get github.com/go-ini/ini
        - go get github.com/olekukonko/tablewriter
        # Run the tests
        - go test
        # Build the binary
        - go build InventoryVisualizer.go
