---
stages:
    - build

build:
    stage: build
    image: golang
    tags:
        - docker
    script:
        - go version
        # Downloading dependencies
        - go get github.com/go-ini/ini
        - go get github.com/olekukonko/tablewriter
        # Build the binary
        - go build InventoryVisualizer.go
        # Run some tests
        - "./InventoryVisualizer test_inventories/{}"
